import type { QuizQuestion } from "@/lib/types";

const quiz01: QuizQuestion[] = [
  {
    id: "q01-1",
    moduleSlug: "01-bem-vindo-atlasgr",
    question: "Em que ano a Atlas Segurança e Inteligência Logística foi fundada?",
    options: ["1998", "2004", "2010", "2015"],
    correctIndex: 1,
    explanation: "A Política Organizacional e Ética afirma que a empresa surgiu em 2004 com o propósito de gerenciar riscos em processos logísticos.",
    reference: "Módulo 1 — Quem é a ATLASGR",
  },
  {
    id: "q01-2",
    moduleSlug: "01-bem-vindo-atlasgr",
    question: "Qual área da Diretoria é descrita como 'o coração da empresa'?",
    options: ["TI", "DHO", "Operações", "Comercial"],
    correctIndex: 2,
    explanation: "Operações é onde as operações de gerenciamento de risco dos clientes efetivamente acontecem — por isso é chamada de coração da empresa.",
    reference: "Módulo 1 — Estrutura Organizacional",
  },
  {
    id: "q01-3",
    moduleSlug: "01-bem-vindo-atlasgr",
    question: "Qual das opções abaixo NÃO é um dos 5 valores da ATLASGR?",
    options: ["Transparência", "Atitude de Dono", "Competitividade", "Simplicidade"],
    correctIndex: 2,
    explanation: "Os 5 valores são Perseverança, Transparência, Simplicidade, Atitude de Dono e Inovação — 'Competitividade' não está entre eles.",
    reference: "Módulo 1 — Quem é a ATLASGR",
  },
  {
    id: "q01-4",
    moduleSlug: "01-bem-vindo-atlasgr",
    question: "De quanto em quanto tempo o Treinamento de Reciclagem é obrigatório, como regra geral?",
    options: ["A cada 1 ano", "A cada 2 anos", "A cada 3 anos", "Apenas uma vez, na admissão"],
    correctIndex: 2,
    explanation: "A reciclagem é obrigatória a cada 3 anos, contados do Treinamento Inicial ou da última reciclagem, podendo ser antecipada em caso de mudanças relevantes.",
    reference: "Módulo 1 — Cultura, ética e conduta",
  },
  {
    id: "q01-5",
    moduleSlug: "01-bem-vindo-atlasgr",
    question: "O uso de celular pessoal é permitido na sala de operação?",
    options: ["Sim, sem restrições", "Não, é expressamente proibido", "Sim, apenas para supervisores", "Sim, apenas durante o intervalo"],
    correctIndex: 1,
    explanation: "A Política Organizacional e Ética proíbe expressamente o uso de celular pessoal na sala de operação.",
    reference: "Módulo 1 — Cultura, ética e conduta",
  },
];

const quiz03: QuizQuestion[] = [
  {
    id: "q03-1",
    moduleSlug: "03-gerenciamento-risco",
    question: "O que é o PGR?",
    options: [
      "Um relatório financeiro mensal",
      "O Plano de Gerenciamento de Risco, com as regras de segurança da operação",
      "Um tipo de sensor do veículo",
      "O nome do sistema de rastreamento",
    ],
    correctIndex: 1,
    explanation: "O PGR define rotas permitidas, horários de risco, pontos de parada e o passo a passo da Central diante de cada tipo de alerta.",
    reference: "Módulo 3 — O que é gerenciamento de risco",
  },
  {
    id: "q03-2",
    moduleSlug: "03-gerenciamento-risco",
    question: "O que é 'sublimite' em uma apólice de seguro?",
    options: [
      "O valor total da apólice",
      "O teto de indenização para uma cobertura específica, dentro do limite geral (LMI)",
      "O nome do relatório de sinistro",
      "Um tipo de alerta do rastreador",
    ],
    correctIndex: 1,
    explanation: "Sublimite é o valor máximo de indenização para uma cobertura específica, dentro do Limite Máximo de Indenização (LMI) geral da apólice.",
    reference: "Módulo 3 — Apólice, sinistro e sublimite",
  },
  {
    id: "q03-3",
    moduleSlug: "03-gerenciamento-risco",
    question: "Quantas permissões uma Gerenciadora de Risco (GR) pode ter ao ser associada a um veículo no portal do fabricante do rastreador?",
    options: ["2", "3", "4", "6"],
    correctIndex: 2,
    explanation: "São 4 permissões: GR Principal, Comando Disponível, Ação Embarcada Disponível e Alerta Compartilhado.",
    reference: "Módulo 3 — A GR dentro do equipamento de rastreamento",
  },
  {
    id: "q03-4",
    moduleSlug: "03-gerenciamento-risco",
    question: "Quantas Gerenciadoras de Risco podem ser marcadas como 'GR Principal' em um mesmo veículo?",
    options: ["Nenhuma", "Apenas uma", "Até duas", "Todas as associadas"],
    correctIndex: 1,
    explanation: "Apenas uma GR pode ser a GR Principal por veículo — ela é responsável pela configuração e gestão do equipamento.",
    reference: "Módulo 3 — A GR dentro do equipamento de rastreamento",
  },
  {
    id: "q03-5",
    moduleSlug: "03-gerenciamento-risco",
    question: "No treinamento de Malícia, o que é a 'senha de coação'?",
    options: [
      "A senha de acesso ao Atlas Connect",
      "Uma palavra combinada previamente para indicar discretamente que o motorista está sendo forçado a agir contra sua vontade",
      "O código do checklist do veículo",
      "A senha do rastreador instalado no veículo",
    ],
    correctIndex: 1,
    explanation: "A senha de coação é combinada entre motorista e Central para sinalizar uma situação de coação sem alertar quem estiver forçando o motorista.",
    reference: "Módulo 3 — Do PGR ao dia a dia da Central",
  },
];

const quiz05: QuizQuestion[] = [
  {
    id: "q05-1",
    moduleSlug: "05-software-logistico",
    question: "Qual afirmação descreve corretamente o Atlas Connect?",
    options: [
      "Ele substitui totalmente o equipamento de rastreamento instalado no veículo",
      "Ele centraliza cadastros, PGR, checklist e eventos, mas não substitui o rastreador",
      "Ele é usado apenas pelo setor Comercial",
      "Ele só funciona para clientes da tecnologia Sascar",
    ],
    correctIndex: 1,
    explanation: "O Connect centraliza o fluxo de trabalho da Central, mas o operador ainda precisa interagir com o equipamento/portal do fabricante do rastreador.",
    reference: "Módulo 5 — O que é o Atlas Connect",
  },
  {
    id: "q05-2",
    moduleSlug: "05-software-logistico",
    question: "Onde o operador solicita um checklist para uma placa específica?",
    options: [
      "Em Usuários do sistema",
      "Em Cadastros Gerais → Veículo → Veículo, no botão 'Solicitar CheckList'",
      "Na Torre de Controle",
      "No Dashboard",
    ],
    correctIndex: 1,
    explanation: "A solicitação é feita a partir do cadastro do veículo, informando responsável e telefone de contato.",
    reference: "Módulo 5 — Fluxo de checklist no Connect",
  },
  {
    id: "q05-3",
    moduleSlug: "05-software-logistico",
    question: "Onde o operador valida item a item os sensores e atuadores testados em um checklist?",
    options: [
      "Em Monitoramento → Operador CheckList",
      "Em Cliente",
      "Em Localização",
      "No menu Logística",
    ],
    correctIndex: 0,
    explanation: "Em Operador CheckList, cada item (bloqueio, sirene, sensores etc.) pode ser aprovado ou reprovado, com campo de observação.",
    reference: "Módulo 5 — Fluxo de checklist no Connect",
  },
  {
    id: "q05-4",
    moduleSlug: "05-software-logistico",
    question: "Quais 3 competências são treinadas em cada tecnologia de rastreamento atendida pela Atlas (ex.: Sascar, Onix, Pósitron)?",
    options: [
      "Vendas, marketing e financeiro",
      "Envio de comandos, desbloqueio manual e análise de relatórios",
      "Instalação física, manutenção e garantia",
      "Cadastro de clientes, faturamento e cobrança",
    ],
    correctIndex: 1,
    explanation: "O cronograma de treinamentos mostra que cada tecnologia (Sascar/Sighra, Onix/Omnilink, Pósitron/Autotrac) é treinada nessas 3 competências.",
    reference: "Módulo 5 — Integração com tecnologias de rastreamento",
  },
  {
    id: "q05-5",
    moduleSlug: "05-software-logistico",
    question: "O que é o 'Consolidado SM' no Atlas Connect?",
    options: [
      "Um relatório de folha de pagamento",
      "A tela que reúne o fechamento das viagens monitoradas (SMs) já concluídas",
      "O cadastro de novos clientes",
      "A lista de sensores de um veículo",
    ],
    correctIndex: 1,
    explanation: "É usada pela liderança para conferir o fechamento das SMs concluídas.",
    reference: "Módulo 5 — Tour pelo menu principal",
  },
];

const quiz02: QuizQuestion[] = [
  {
    id: "q02-1",
    moduleSlug: "02-mercado-logistica",
    question: "Qual das opções abaixo descreve corretamente um embarcador?",
    options: [
      "Empresa que executa o transporte contratando frota e motoristas",
      "Dono da carga: fabricante, distribuidor ou varejista que precisa transportar seu produto",
      "Órgão regulador do transporte rodoviário",
      "Sistema de rastreamento instalado no veículo",
    ],
    correctIndex: 1,
    explanation: "Embarcador é o dono da carga; quem executa o transporte é a transportadora.",
    reference: "Módulo 2 — A cadeia de suprimentos e seus elos",
  },
  {
    id: "q02-2",
    moduleSlug: "02-mercado-logistica",
    question: "Qual tipo de carga costuma exigir regras adicionais de segurança e resposta a emergência, como o MOPP?",
    options: ["Carga fracionada", "Carga perecível", "Carga perigosa (combustíveis, químicos)", "Granel sólido"],
    correctIndex: 2,
    explanation: "Cargas perigosas, como combustíveis e químicos, exigem regras adicionais de segurança, incluindo o MOPP.",
    reference: "Módulo 2 — Tipos de carga e perfil de risco",
  },
  {
    id: "q02-3",
    moduleSlug: "02-mercado-logistica",
    question: "Qual a diferença entre o TMS do cliente e o Atlas Connect?",
    options: [
      "São o mesmo sistema com nomes diferentes",
      "O TMS cuida do planejamento logístico; o Connect cuida do gerenciamento de risco",
      "O TMS substitui totalmente o Connect",
      "O Connect é usado apenas pelo setor comercial do cliente",
    ],
    correctIndex: 1,
    explanation: "O TMS é do cliente e cuida do planejamento logístico; o Atlas Connect é da Atlas e cuida do gerenciamento de risco.",
    reference: "Módulo 2 — Sistemas de gestão que conversam com a Atlas",
  },
  {
    id: "q02-4",
    moduleSlug: "02-mercado-logistica",
    question: "Segundo dados públicos da CNT, qual modal predomina no transporte de cargas no Brasil?",
    options: ["Ferroviário", "Rodoviário", "Aquaviário", "Dutoviário"],
    correctIndex: 1,
    explanation: "Cerca de 65% das cargas no Brasil são transportadas por rodovia, segundo a CNT.",
    reference: "Módulo 2 — O transporte de cargas no Brasil em números",
  },
  {
    id: "q02-5",
    moduleSlug: "02-mercado-logistica",
    question: "Por que o mesmo veículo pode ter regras vindas tanto da transportadora quanto do embarcador?",
    options: [
      "Porque o PGR da transportadora e as exigências específicas do embarcador daquela carga podem coexistir",
      "Porque o veículo troca de dono a cada viagem",
      "Porque a Atlas exige isso por padrão em todos os contratos",
      "Isso nunca acontece na prática",
    ],
    correctIndex: 0,
    explanation: "É comum que o PGR da transportadora conviva com regras adicionais exigidas pelo embarcador de uma carga específica.",
    reference: "Módulo 2 — A cadeia de suprimentos e seus elos",
  },
];

const quiz04: QuizQuestion[] = [
  {
    id: "q04-1",
    moduleSlug: "04-produtos-atlasgr",
    question: "Quais são os quatro pilares do portfólio ATLASGR?",
    options: [
      "Vendas, Marketing, Financeiro e RH",
      "Profile, GR, Connect e Analytics",
      "Implantação, Operação, CIA e Supervisão",
      "TMS, ERP, API e KPI",
    ],
    correctIndex: 1,
    explanation: "O portfólio se organiza em quatro pilares: Atlas Profile, Atlas GR, Atlas Connect e Atlas Analytics.",
    reference: "Módulo 4 — Os quatro pilares do portfólio",
  },
  {
    id: "q04-2",
    moduleSlug: "04-produtos-atlasgr",
    question: "Qual pilar resolve o 'custo invisível' da contratação irregular?",
    options: ["Atlas Analytics", "Atlas Connect", "Atlas Profile", "Atlas GR"],
    correctIndex: 2,
    explanation: "O Atlas Profile valida documentação, antecedentes e biometria antes da viagem, endereçando o custo invisível da contratação.",
    reference: "Módulo 4 — Atlas Profile — Background Check",
  },
  {
    id: "q04-3",
    moduleSlug: "04-produtos-atlasgr",
    question: "Qual é o núcleo histórico da empresa, responsável pela aderência à apólice e pela CIA?",
    options: ["Atlas Analytics", "Atlas GR", "Atlas Connect", "Atlas Profile"],
    correctIndex: 1,
    explanation: "Atlas GR garante que a operação segue a apólice e o PGR, com a CIA tratando qualquer desvio.",
    reference: "Módulo 4 — Atlas GR — Aderência à apólice e CIA",
  },
  {
    id: "q04-4",
    moduleSlug: "04-produtos-atlasgr",
    question: "Qual a principal diferença entre Atlas Connect e Atlas Analytics?",
    options: [
      "Não há diferença, são o mesmo produto",
      "Connect é tempo real e operacional; Analytics é histórico e executivo",
      "Connect é usado só pelo Comercial; Analytics só pela CIA",
      "Analytics substitui o Connect em clientes grandes",
    ],
    correctIndex: 1,
    explanation: "Connect tem foco operacional em tempo real; Analytics consolida o histórico em painéis executivos.",
    reference: "Módulo 4 — Atlas Connect e Atlas Analytics",
  },
  {
    id: "q04-5",
    moduleSlug: "04-produtos-atlasgr",
    question: "O case do embarcador de combustível (R$ 95M economizados) está associado a qual tipo de dor?",
    options: [
      "Falta de indicadores executivos",
      "Prejuízo direto com roubo de carga de alto valor",
      "Tempo parado em fazendas",
      "Falta de integração com TMS",
    ],
    correctIndex: 1,
    explanation: "O case de R$ 95M em perdas evitadas está ligado à redução do prejuízo direto com roubo de carga.",
    reference: "Módulo 4 — Atlas Connect e Atlas Analytics",
  },
];

const quiz06: QuizQuestion[] = [
  {
    id: "q06-1",
    moduleSlug: "06-atlas-profile",
    question: "O que o texto do módulo chama de 'custo invisível' da contratação?",
    options: [
      "O custo de combustível do veículo",
      "Um risco que não aparece em relatório até virar um problema grave",
      "O custo do treinamento do motorista",
      "O valor do seguro RCF-DC",
    ],
    correctIndex: 1,
    explanation: "O custo invisível é o risco de uma contratação malfeita que só se manifesta quando já é tarde — um sinistro grave ou acidente.",
    reference: "Módulo 6 — O custo invisível da contratação",
  },
  {
    id: "q06-2",
    moduleSlug: "06-atlas-profile",
    question: "O que a validação por FaceID confirma no processo do Atlas Profile?",
    options: [
      "Que o veículo está com o seguro em dia",
      "Que a pessoa que vai dirigir é a mesma que foi cadastrada e aprovada",
      "Que a carga está corretamente lacrada",
      "Que o PGR do cliente foi atualizado",
    ],
    correctIndex: 1,
    explanation: "A validação biométrica (FaceID) garante que a pessoa que dirige é de fato quem foi cadastrada e aprovada.",
    reference: "Módulo 6 — O que o Atlas Profile verifica",
  },
  {
    id: "q06-3",
    moduleSlug: "06-atlas-profile",
    question: "O que significa um cadastro classificado como 'Requer Atenção'?",
    options: [
      "O motorista está automaticamente reprovado",
      "Um analista do Perfil Securitário precisa avaliar o caso antes de qualquer decisão",
      "O veículo será removido da frota",
      "Não é necessária nenhuma ação adicional",
    ],
    correctIndex: 1,
    explanation: "'Requer Atenção' sinaliza que um analista humano precisa avaliar o caso — o sistema não decide sozinho.",
    reference: "Módulo 6 — Quando um cadastro é classificado como 'Requer Atenção'",
  },
  {
    id: "q06-4",
    moduleSlug: "06-atlas-profile",
    question: "Por que o Atlas Profile precisa seguir a LGPD com rigor?",
    options: [
      "Porque lida com dados pessoais sensíveis, como documentos e biometria",
      "Porque é exigido apenas para clientes do setor público",
      "Porque a LGPD só se aplica a dados financeiros",
      "A LGPD não se aplica ao Atlas Profile",
    ],
    correctIndex: 0,
    explanation: "O Atlas Profile trata documentos, biometria e histórico de processos — todos dados pessoais sensíveis sujeitos à LGPD.",
    reference: "Módulo 6 — Atlas Profile e a LGPD",
  },
  {
    id: "q06-5",
    moduleSlug: "06-atlas-profile",
    question: "Segundo o módulo, o que frequentemente está na origem de acidentes graves envolvendo veículos de carga?",
    options: [
      "Falhas exclusivamente mecânicas do veículo",
      "Uma falha de contratação que passou despercebida",
      "Condições climáticas imprevisíveis",
      "Falta de combustível",
    ],
    correctIndex: 1,
    explanation: "Documentação vencida ou histórico não investigado antes da liberação são falhas de contratação que costumam estar na origem de acidentes graves.",
    reference: "Módulo 6 — Quando um cadastro é classificado como 'Requer Atenção'",
  },
];

const quiz07: QuizQuestion[] = [
  {
    id: "q07-1",
    moduleSlug: "07-integracoes",
    question: "Por que o Atlas Connect precisa integrar com sistemas de terceiros?",
    options: [
      "Porque a Atlas não fabrica o equipamento de rastreamento instalado no veículo",
      "Porque é uma exigência da LGPD",
      "Porque o Connect não funciona sozinho",
      "Porque todo cliente exige isso por contrato",
    ],
    correctIndex: 0,
    explanation: "A Atlas integra com rastreadores de diferentes fabricantes para captar posição, eventos e comandos dentro do Connect.",
    reference: "Módulo 7 — Por que o Connect precisa conversar com outros sistemas",
  },
  {
    id: "q07-2",
    moduleSlug: "07-integracoes",
    question: "Quais das opções abaixo são tecnologias de rastreamento integradas à Atlas?",
    options: [
      "Sascar/Sighra, Onix/Omnilink, Pósitron/Autotrac",
      "SAP, Oracle e Salesforce",
      "AWS, Azure e Google Cloud",
      "WhatsApp, Telegram e Slack",
    ],
    correctIndex: 0,
    explanation: "Sascar/Sighra, Onix/Omnilink e Pósitron/Autotrac são as tecnologias de rastreamento citadas como integradas à Atlas.",
    reference: "Módulo 7 — Tecnologias de rastreamento integradas",
  },
  {
    id: "q07-3",
    moduleSlug: "07-integracoes",
    question: "Quais são as três competências treinadas para cada tecnologia de rastreamento?",
    options: [
      "Vendas, marketing e financeiro",
      "Envio de comandos, desbloqueio manual e leitura de relatórios",
      "Instalação física, manutenção e garantia",
      "Cadastro, faturamento e cobrança",
    ],
    correctIndex: 1,
    explanation: "Para cada tecnologia, o operador domina envio de comandos, desbloqueio manual e leitura de relatórios de eventos.",
    reference: "Módulo 7 — Tecnologias de rastreamento integradas",
  },
  {
    id: "q07-4",
    moduleSlug: "07-integracoes",
    question: "O que acontece se a integração do Connect com o TMS do cliente falhar?",
    options: [
      "O monitoramento de risco para completamente",
      "O monitoramento continua normal; só o reflexo automático de dados no TMS fica indisponível",
      "A CIA é acionada automaticamente",
      "Todos os veículos ficam bloqueados",
    ],
    correctIndex: 1,
    explanation: "Falha na integração com TMS/ERP afeta a visibilidade do cliente, mas não interrompe o monitoramento de risco.",
    reference: "Módulo 7 — Dois tipos de integração, dois tipos de risco",
  },
  {
    id: "q07-5",
    moduleSlug: "07-integracoes",
    question: "O que acontece quando o rastreador do veículo perde sinal?",
    options: [
      "É ignorado até o fim da viagem",
      "É um evento crítico, tratado dentro do fluxo de gerenciamento de risco",
      "Só é tratado se o cliente ligar reclamando",
      "Gera apenas um e-mail automático sem tratativa",
    ],
    correctIndex: 1,
    explanation: "Perda de sinal é um evento crítico; perda superior a 2 horas é escalada para a CIA II.",
    reference: "Módulo 7 — Dois tipos de integração, dois tipos de risco",
  },
];

const quiz08: QuizQuestion[] = [
  {
    id: "q08-1",
    moduleSlug: "08-clientes",
    question: "Quais são os três perfis principais de cliente atendidos pela Atlas?",
    options: [
      "Governo, ONGs e pessoas físicas",
      "Transportadora, embarcador e operador logístico",
      "Bancos, seguradoras e fintechs",
      "Fabricantes de rastreador, TMS e ERP",
    ],
    correctIndex: 1,
    explanation: "Os três perfis principais são transportadora, embarcador e operador logístico.",
    reference: "Módulo 8 — Quem contrata a Atlas",
  },
  {
    id: "q08-2",
    moduleSlug: "08-clientes",
    question: "Qual é a dor principal mais associada a uma transportadora?",
    options: [
      "Visibilidade da carga transportada por terceiros",
      "Cumprir exigências de apólice e reduzir prejuízo direto com sinistro",
      "Indicadores executivos de tempo parado",
      "Escolha de fornecedor de combustível",
    ],
    correctIndex: 1,
    explanation: "A transportadora costuma focar em cumprir exigências de apólice e reduzir prejuízo direto com sinistros.",
    reference: "Módulo 8 — Quem contrata a Atlas",
  },
  {
    id: "q08-3",
    moduleSlug: "08-clientes",
    question: "O que caracteriza o perfil de 'operador logístico'?",
    options: [
      "É sempre o menor cliente da Atlas",
      "Atua entre transportadora e embarcador, combinando visão operacional e executiva",
      "Só usa o Atlas Analytics, nunca o Connect",
      "Não tem relação direta com a Atlas",
    ],
    correctIndex: 1,
    explanation: "O operador logístico atua por conta de um ou mais embarcadores e costuma precisar tanto do Connect quanto do Analytics.",
    reference: "Módulo 8 — Quem contrata a Atlas",
  },
  {
    id: "q08-4",
    moduleSlug: "08-clientes",
    question: "O case de -26% de tempo em fazendas está mais associado a qual tipo de dor?",
    options: [
      "Prejuízo direto com roubo de carga",
      "Custo operacional invisível (tempo parado)",
      "Falta de apólice de seguro",
      "Falha de biometria facial",
    ],
    correctIndex: 1,
    explanation: "O embarcador de suco identificou tempo parado como um custo operacional invisível, reduzido em 26%.",
    reference: "Módulo 8 — A dor de cada perfil, na prática",
  },
  {
    id: "q08-5",
    moduleSlug: "08-clientes",
    question: "O que o módulo quer dizer com 'o mesmo produto, dores diferentes'?",
    options: [
      "Cada cliente precisa de um produto exclusivo e diferente",
      "Connect e Analytics podem resolver dores diferentes dependendo do perfil do cliente",
      "A Atlas nunca reutiliza cases entre clientes",
      "Produtos diferentes sempre resolvem a mesma dor",
    ],
    correctIndex: 1,
    explanation: "Os mesmos produtos (Connect e Analytics) resolveram dores diferentes nos cases de combustível e suco.",
    reference: "Módulo 8 — A dor de cada perfil, na prática",
  },
];

const quiz09: QuizQuestion[] = [
  {
    id: "q09-1",
    moduleSlug: "09-processo-comercial",
    question: "O que é o ICP no processo comercial?",
    options: [
      "Um tipo de apólice de seguro",
      "O perfil de cliente ideal para a Atlas prospectar",
      "Um sistema de rastreamento",
      "Um indicador de desempenho da Central",
    ],
    correctIndex: 1,
    explanation: "ICP (Ideal Customer Profile) descreve o tipo de empresa ideal para a Atlas prospectar.",
    reference: "Módulo 9 — ICP e persona: para quem a Atlas vende",
  },
  {
    id: "q09-2",
    moduleSlug: "09-processo-comercial",
    question: "Qual das opções abaixo NÃO é citada como uma dor comum que abre a conversa comercial?",
    options: [
      "Exigência contratual de rastreamento e PGR",
      "Histórico recente de sinistro",
      "Preferência por uma cor específica de veículo",
      "Custo operacional invisível",
    ],
    correctIndex: 2,
    explanation: "Preferência por cor de veículo não é uma dor relevante para o gerenciamento de risco; as demais são dores reais citadas no módulo.",
    reference: "Módulo 9 — Dores comuns e argumentação",
  },
  {
    id: "q09-3",
    moduleSlug: "09-processo-comercial",
    question: "Como responder à objeção 'já temos rastreador, para que contratar a Atlas'?",
    options: [
      "Concordar que o rastreador já é suficiente",
      "Explicar que o rastreador é só o ponto de partida; a Atlas entrega PGR, tratativa 24h e CIA",
      "Oferecer desconto imediato sem argumentar",
      "Encerrar a conversa, pois não há argumento possível",
    ],
    correctIndex: 1,
    explanation: "O rastreador capta dados; a Atlas transforma isso em gerenciamento de risco completo.",
    reference: "Módulo 9 — Objeções mais comuns",
  },
  {
    id: "q09-4",
    moduleSlug: "09-processo-comercial",
    question: "Qual é o diferencial competitivo da Atlas, segundo o módulo?",
    options: [
      "Apenas o preço mais baixo do mercado",
      "A combinação de tecnologia, pessoas especializadas e processo estruturado",
      "Ser a única empresa com rastreador no Brasil",
      "Atender exclusivamente grandes embarcadores",
    ],
    correctIndex: 1,
    explanation: "O diferencial é a combinação de tecnologia (Connect), pessoas (CIA) e processo (PGR) funcionando juntos.",
    reference: "Módulo 9 — Objeções mais comuns",
  },
  {
    id: "q09-5",
    moduleSlug: "09-processo-comercial",
    question: "Por que todo colaborador, e não só o time Comercial, precisa entender o discurso comercial?",
    options: [
      "Porque todos são avaliados por metas de vendas",
      "Porque qualquer colaborador pode conversar com um cliente e uma contradição gera problema para o Comercial resolver depois",
      "Porque é uma exigência legal",
      "Não há motivo real, é apenas uma boa prática",
    ],
    correctIndex: 1,
    explanation: "Um colaborador que promete algo fora do contrato, por exemplo, cria um problema que o Comercial precisa resolver depois.",
    reference: "Módulo 9 — Todo colaborador representa a marca",
  },
];

const quiz10: QuizQuestion[] = [
  {
    id: "q10-1",
    moduleSlug: "10-termos-tecnicos",
    question: "Em qual categoria o módulo classifica os termos PGR, sinistro e sublimite?",
    options: ["Termos operacionais da Central", "Termos de risco e seguro", "Termos de mercado e tecnologia", "Termos regulatórios"],
    correctIndex: 1,
    explanation: "PGR, sinistro e sublimite são classificados como termos de risco e seguro.",
    reference: "Módulo 10 — Termos de risco e seguro",
  },
  {
    id: "q10-2",
    moduleSlug: "10-termos-tecnicos",
    question: "Onde é possível consultar a definição completa de qualquer termo técnico a qualquer momento?",
    options: ["Apenas neste módulo", "No Glossário do portal, disponível no menu principal", "Apenas perguntando ao supervisor", "Não há um local centralizado"],
    correctIndex: 1,
    explanation: "O Glossário do portal é a referência rápida disponível a qualquer momento pelo menu principal.",
    reference: "Módulo 10 — Por que este módulo existe",
  },
  {
    id: "q10-3",
    moduleSlug: "10-termos-tecnicos",
    question: "Qual das opções é uma sigla interna da Atlas, e não um termo genérico de mercado?",
    options: ["TMS", "KPI", "SM", "SLA"],
    correctIndex: 2,
    explanation: "SM é uma sigla interna da Atlas (registro de viagem monitorada); TMS, KPI e SLA são termos de mercado.",
    reference: "Módulo 10 — Termos regulatórios e institucionais",
  },
  {
    id: "q10-4",
    moduleSlug: "10-termos-tecnicos",
    question: "Em qual categoria se encaixam ANTT, CNT, SUSEP e LGPD?",
    options: ["Termos operacionais da Central", "Termos de risco e seguro", "Termos regulatórios e institucionais", "Termos de mercado e tecnologia"],
    correctIndex: 2,
    explanation: "ANTT, CNT, SUSEP e LGPD são órgãos e normas — termos regulatórios e institucionais.",
    reference: "Módulo 10 — Termos regulatórios e institucionais",
  },
  {
    id: "q10-5",
    moduleSlug: "10-termos-tecnicos",
    question: "KPI é um exemplo de termo de qual categoria?",
    options: ["Termos de risco e seguro", "Termos operacionais da Central", "Termos de mercado e tecnologia", "Termos regulatórios"],
    correctIndex: 2,
    explanation: "KPI é um termo amplamente usado no mercado de gestão, classificado como termo de mercado e tecnologia.",
    reference: "Módulo 10 — Termos de mercado e tecnologia",
  },
];

const quiz11: QuizQuestion[] = [
  {
    id: "q11-1",
    moduleSlug: "11-operacao",
    question: "O que o operador deve solicitar antes de tratar qualquer assunto em uma ligação recebida?",
    options: ["O número do PGR do cliente", "A confirmação da senha de voz", "O CPF completo do motorista", "O código da SM por escrito"],
    correctIndex: 1,
    explanation: "Sem a confirmação da senha de voz, o atendimento deve ser encerrado, mesmo que o interlocutor diga ser o motorista ou responsável.",
    reference: "Módulo 11 — A rotina de um operador",
  },
  {
    id: "q11-2",
    moduleSlug: "11-operacao",
    question: "No Atlas Connect, o que define a ordem de tratativa dos alertas na Torre de Controle?",
    options: [
      "A ordem de chegada do alerta",
      "O nível de prioridade fixo do tipo de evento (1 a 7)",
      "A preferência pessoal do operador",
      "O horário do turno",
    ],
    correctIndex: 1,
    explanation: "Cada tipo de evento tem um nível de prioridade fixo, de 1 a 7, que organiza a fila de tratativa — não a ordem de chegada.",
    reference: "Módulo 11 — Os 7 níveis de prioridade de alerta",
  },
  {
    id: "q11-3",
    moduleSlug: "11-operacao",
    question: "O que acontece quando um veículo está simultaneamente em Perda de Sinal (nível 6) e Desvio de Rota (nível 5)?",
    options: [
      "Abrem-se dois atendimentos separados, um para cada nível",
      "O nível 6 sempre sobrepõe o nível 5: o operador segue o procedimento de Perda de Sinal primeiro",
      "O nível 5 sempre sobrepõe o nível 6",
      "O sistema ignora automaticamente o alerta de menor nível",
    ],
    correctIndex: 1,
    explanation: "O nível 6 (Perda de Sinal) sempre sobrepõe o nível 5 (Desvio de Rota) — o operador trata primeiro a Perda de Sinal, começando pelo envio de comando de posição e mensagem.",
    reference: "Módulo 11 — Os 7 níveis de prioridade de alerta",
  },
  {
    id: "q11-4",
    moduleSlug: "11-operacao",
    question: "Qual é o SLA real de tratativa de um evento crítico, segundo o procedimento padronizado?",
    options: [
      "Início em até 30 minutos, conclusão em até 2 horas",
      "Início em até 10 minutos, conclusão em até 45 minutos",
      "Início em até 1 hora, sem prazo de conclusão",
      "Não há prazo definido, depende do operador",
    ],
    correctIndex: 1,
    explanation: "O procedimento padronizado exige início da tratativa em até 10 minutos e conclusão em até 45 minutos.",
    reference: "Módulo 11 — SLA e roteiro de escalonamento",
  },
  {
    id: "q11-5",
    moduleSlug: "11-operacao",
    question: "No roteiro padrão de escalonamento, o que acontece logo antes do acionamento de autoridades policiais?",
    options: [
      "Envio do comando 'Bloqueio', caso o veículo esteja parado",
      "Registro de Não Conformidade",
      "Contato para autorizar Pronta Resposta",
      "Envio de mensagem inicial ao motorista",
    ],
    correctIndex: 0,
    explanation: "O roteiro é: mensagem → tentativa de contato → Liga Sirene → contato com cliente → Bloqueio → acionamento policial → registro de Não Conformidade → autorização de Pronta Resposta.",
    reference: "Módulo 11 — SLA e roteiro de escalonamento",
  },
];

const quiz12: QuizQuestion[] = [
  {
    id: "q12-1",
    moduleSlug: "12-compliance",
    question: "Por que compliance é responsabilidade de todo colaborador na Atlas?",
    options: [
      "Porque só afeta o setor jurídico",
      "Porque a Atlas lida diariamente com dados sensíveis de localização, documentos e sinistros",
      "Porque é uma exigência apenas para cargos de liderança",
      "Compliance não é relevante para a operação do dia a dia",
    ],
    correctIndex: 1,
    explanation: "Dados sensíveis tratados diariamente tornam compliance responsabilidade de todos, não só de um setor.",
    reference: "Módulo 12 — Por que compliance importa na Atlas",
  },
  {
    id: "q12-2",
    moduleSlug: "12-compliance",
    question: "O que a LGPD exige para o tratamento de dados pessoais?",
    options: [
      "Nenhuma exigência específica",
      "Finalidade clara e, em muitos casos, consentimento do titular",
      "Apenas armazenamento em nuvem estrangeira",
      "Aprovação prévia da ANTT",
    ],
    correctIndex: 1,
    explanation: "A LGPD exige finalidade clara e, em muitos casos, consentimento para o tratamento de dados pessoais.",
    reference: "Módulo 12 — LGPD no dia a dia da operação",
  },
  {
    id: "q12-3",
    moduleSlug: "12-compliance",
    question: "Desde a Lei nº 14.599/2023, quais são os três seguros obrigatórios para o transportador rodoviário de cargas?",
    options: [
      "RCTR-C, RC-DC e RC-V",
      "LGPD, PGR e SLA",
      "TMS, ERP e API",
      "Apenas o seguro de responsabilidade civil, como antes",
    ],
    correctIndex: 0,
    explanation: "A Lei nº 14.599/2023 tornou obrigatórios os três seguros: RCTR-C, RC-DC e RC-V, vinculados ao RNTRC e ao PGR.",
    reference: "Módulo 12 — A Lei nº 14.599/2023 e os seguros obrigatórios de carga",
  },
  {
    id: "q12-4",
    moduleSlug: "12-compliance",
    question: "É permitido comentar em redes sociais sobre um caso real atendido, sem citar nomes?",
    options: [
      "Sim, sempre que não houver nomes",
      "Não — detalhes como local, data ou tipo de carga podem identificar o caso mesmo sem nomes",
      "Sim, mas apenas fora do horário de trabalho",
      "Depende apenas da aprovação do cliente",
    ],
    correctIndex: 1,
    explanation: "Mesmo sem nomes, detalhes podem identificar o cliente ou caso — a orientação é não comentar casos reais fora do trabalho.",
    reference: "Módulo 12 — Sigilo, e-mail, internet e redes sociais",
  },
  {
    id: "q12-5",
    moduleSlug: "12-compliance",
    question: "Qual é uma consequência possível de uma falha de compliance, segundo o módulo?",
    options: [
      "Nenhuma, é apenas uma questão administrativa",
      "Notificação à ANPD e até rescisão contratual com o cliente afetado",
      "Apenas um advertência verbal sem outros efeitos",
      "Aumento automático de faturamento",
    ],
    correctIndex: 1,
    explanation: "Falhas de compliance podem gerar notificação à ANPD, rescisão contratual e dano reputacional.",
    reference: "Módulo 12 — Sigilo, e-mail, internet e redes sociais",
  },
];

const quiz13: QuizQuestion[] = [
  {
    id: "q13-1",
    moduleSlug: "13-tecnologia",
    question: "Qual é a diferença entre monitoramento reativo e prevenção baseada em dados?",
    options: [
      "Não há diferença prática",
      "Reativo trata depois do evento; prevenção antecipa o risco antes que ele aconteça",
      "Prevenção baseada em dados é mais lenta que o reativo",
      "Reativo é exclusivo de clientes pequenos",
    ],
    correctIndex: 1,
    explanation: "O reativo trata alertas após o evento; a prevenção usa dados para antecipar onde o risco é maior.",
    reference: "Módulo 13 — De reativo para preditivo",
  },
  {
    id: "q13-2",
    moduleSlug: "13-tecnologia",
    question: "O que o sensor de Safety identifica em tempo real?",
    options: [
      "Apenas a velocidade do veículo",
      "Sinais de fadiga, distração ou risco de colisão do motorista",
      "O nível de combustível",
      "A temperatura da carga",
    ],
    correctIndex: 1,
    explanation: "O Safety identifica sinais como bocejo, olhos fechados e uso de celular, indicando fadiga ou distração.",
    reference: "Módulo 13 — Safety: um exemplo de tecnologia já em uso",
  },
  {
    id: "q13-3",
    moduleSlug: "13-tecnologia",
    question: "O que o Atlas Analytics consolida?",
    options: [
      "Apenas o cadastro de motoristas",
      "Eventos, alertas e indicadores de KPI em painéis executivos",
      "Somente dados financeiros da Atlas",
      "Apenas o histórico de treinamentos dos colaboradores",
    ],
    correctIndex: 1,
    explanation: "O Atlas Analytics consolida eventos, alertas e KPIs em painéis executivos de tendência.",
    reference: "Módulo 13 — Atlas Analytics e o papel da IA",
  },
  {
    id: "q13-4",
    moduleSlug: "13-tecnologia",
    question: "Qual é o papel da inteligência artificial citado no módulo?",
    options: [
      "Substituir totalmente a CIA",
      "Reconhecer padrões em grandes volumes de eventos para tornar a prevenção mais precisa",
      "Eliminar a necessidade de PGR",
      "Substituir o time comercial",
    ],
    correctIndex: 1,
    explanation: "A IA aplicada a grandes volumes de eventos é uma tendência para tornar a prevenção mais precisa, sem substituir processo.",
    reference: "Módulo 13 — Atlas Analytics e o papel da IA",
  },
  {
    id: "q13-5",
    moduleSlug: "13-tecnologia",
    question: "Tecnologia de análise de dados substitui um PGR bem desenhado ou uma CIA bem treinada?",
    options: [
      "Sim, totalmente",
      "Não — ela torna o processo mais preciso e mais rápido, não o substitui",
      "Sim, mas apenas para clientes pequenos",
      "Depende exclusivamente do orçamento do cliente",
    ],
    correctIndex: 1,
    explanation: "O módulo é explícito: tecnologia não substitui PGR nem CIA, apenas torna o processo mais preciso e rápido.",
    reference: "Módulo 13 — Atlas Analytics e o papel da IA",
  },
];

const quiz14: QuizQuestion[] = [
  {
    id: "q14-1",
    moduleSlug: "14-casos-reais",
    question: "O case de R$ 95M economizados está associado a qual tipo de cliente?",
    options: ["Embarcador de suco", "Embarcador de combustível", "Operação de varejo", "Operador logístico de eletrônicos"],
    correctIndex: 1,
    explanation: "O embarcador de combustível é o cliente associado ao case de R$ 95M economizados em perdas.",
    reference: "Módulo 14 — Resultados documentados com cliente",
  },
  {
    id: "q14-2",
    moduleSlug: "14-casos-reais",
    question: "O que o case do embarcador de suco (-26%) mediu?",
    options: [
      "Redução no valor do frete",
      "Redução no tempo de permanência de veículos em fazendas",
      "Redução no número de motoristas contratados",
      "Redução no consumo de combustível",
    ],
    correctIndex: 1,
    explanation: "O case mediu a redução de 26% no tempo de permanência de veículos em fazendas.",
    reference: "Módulo 14 — Resultados documentados com cliente",
  },
  {
    id: "q14-3",
    moduleSlug: "14-casos-reais",
    question: "O que representa o resultado de 99,8% no case 'Operação Varejo'?",
    options: [
      "Percentual de motoristas aprovados no Atlas Profile",
      "Aderência às exigências da apólice contratada",
      "Percentual de entregas no prazo",
      "Percentual de veículos com rastreador instalado",
    ],
    correctIndex: 1,
    explanation: "O resultado de 99,8% representa a aderência às exigências da apólice contratada pelo cliente de varejo.",
    reference: "Módulo 14 — Resultados documentados com cliente",
  },
  {
    id: "q14-4",
    moduleSlug: "14-casos-reais",
    question: "Como o módulo descreve o cenário 'Operação Pôr do Sol'?",
    options: [
      "Um caso real de cliente, com nome divulgado publicamente",
      "Um cenário ilustrativo de treinamento, sem relação com cliente específico",
      "Um relatório financeiro trimestral",
      "Um produto do portfólio ATLASGR",
    ],
    correctIndex: 1,
    explanation: "O módulo deixa explícito que é um cenário ilustrativo de treinamento, não um evento real específico.",
    reference: "Módulo 14 — Cenário ilustrativo: da perda de sinal ao acionamento da CIA",
  },
  {
    id: "q14-5",
    moduleSlug: "14-casos-reais",
    question: "Com base em que o Atlas Analytics classifica trechos de rodovia por nível de risco?",
    options: [
      "Opinião pessoal dos operadores",
      "Histórico de eventos registrados naquela região",
      "Sorteio aleatório mensal",
      "Preço do pedágio do trecho",
    ],
    correctIndex: 1,
    explanation: "A classificação é baseada em dados acumulados de ocorrências históricas, não em opinião.",
    reference: "Módulo 14 — Por que algumas rodovias concentram mais risco",
  },
];

const quiz15: QuizQuestion[] = [
  {
    id: "q15-1",
    moduleSlug: "15-preparacao-final",
    question: "Quais são os quatro pilares do portfólio ATLASGR, revisados neste módulo?",
    options: [
      "Vendas, Marketing, TI e RH",
      "Atlas Profile, Atlas GR, Atlas Connect e Atlas Analytics",
      "Implantação, CIA, Supervisão e Comercial",
      "TMS, ERP, API e KPI",
    ],
    correctIndex: 1,
    explanation: "Os quatro pilares revisados são Atlas Profile, Atlas GR, Atlas Connect e Atlas Analytics.",
    reference: "Módulo 15 — Revisão por bloco de conteúdo",
  },
  {
    id: "q15-2",
    moduleSlug: "15-preparacao-final",
    question: "Qual é o fluxo geral reforçado na revisão final?",
    options: [
      "Analytics define a regra, PGR mede o resultado",
      "PGR define a regra, Connect e Profile aplicam no dia a dia, CIA trata a exceção, Analytics mede o resultado",
      "CIA define a regra, PGR trata a exceção",
      "Não existe um fluxo único entre os módulos",
    ],
    correctIndex: 1,
    explanation: "Esse é o fio condutor reforçado: PGR → Connect/Profile → CIA → Analytics.",
    reference: "Módulo 15 — Revisão por bloco de conteúdo",
  },
  {
    id: "q15-3",
    moduleSlug: "15-preparacao-final",
    question: "Qual é a nota mínima de aprovação da Prova Final?",
    options: ["50%", "60%", "70%", "90%"],
    correctIndex: 2,
    explanation: "A aprovação na Prova Final exige 70% de acerto.",
    reference: "Módulo 15 — Antes de fazer a Prova Final",
  },
  {
    id: "q15-4",
    moduleSlug: "15-preparacao-final",
    question: "Em qual bloco de conteúdo o módulo 'Compliance' foi agrupado na revisão final?",
    options: ["Empresa e mercado", "Risco e produtos", "Tecnologia e operação", "Governança e casos"],
    correctIndex: 3,
    explanation: "Compliance foi agrupado, junto com Termos Técnicos e Casos Reais, no bloco 'Governança e casos'.",
    reference: "Módulo 15 — Revisão por bloco de conteúdo",
  },
  {
    id: "q15-5",
    moduleSlug: "15-preparacao-final",
    question: "Qual é o objetivo central do módulo 'Preparação Final'?",
    options: [
      "Introduzir conteúdo totalmente novo, não visto antes",
      "Revisar os pontos-chave de todos os módulos antes da Prova Final",
      "Substituir a necessidade de fazer a Prova Final",
      "Ensinar um quinto pilar do portfólio",
    ],
    correctIndex: 1,
    explanation: "O módulo 15 existe para consolidar a revisão de tudo o que já foi estudado, preparando para a Prova Final.",
    reference: "Módulo 15 — Antes de fazer a Prova Final",
  },
];

export const quizzesByModule: Record<string, QuizQuestion[]> = {
  "01-bem-vindo-atlasgr": quiz01,
  "02-mercado-logistica": quiz02,
  "03-gerenciamento-risco": quiz03,
  "04-produtos-atlasgr": quiz04,
  "05-software-logistico": quiz05,
  "06-atlas-profile": quiz06,
  "07-integracoes": quiz07,
  "08-clientes": quiz08,
  "09-processo-comercial": quiz09,
  "10-termos-tecnicos": quiz10,
  "11-operacao": quiz11,
  "12-compliance": quiz12,
  "13-tecnologia": quiz13,
  "14-casos-reais": quiz14,
  "15-preparacao-final": quiz15,
};

export function getQuizForModule(slug: string): QuizQuestion[] {
  return quizzesByModule[slug] ?? [];
}

export function getAllBuiltQuestions(): QuizQuestion[] {
  return [
    ...quiz01,
    ...quiz02,
    ...quiz03,
    ...quiz04,
    ...quiz05,
    ...quiz06,
    ...quiz07,
    ...quiz08,
    ...quiz09,
    ...quiz10,
    ...quiz11,
    ...quiz12,
    ...quiz13,
    ...quiz14,
    ...quiz15,
  ];
}

export function shuffle<T>(arr: T[]): T[] {
  const copy = [...arr];
  for (let i = copy.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [copy[i], copy[j]] = [copy[j], copy[i]];
  }
  return copy;
}
