import { question as q } from "./helpers";

export const quiz01 = [
  q("01-bem-vindo-atlasgr", 1, "Um cliente pede uma exceção urgente que pode afetar segurança ou contrato. Qual é a melhor primeira ação?", ["Prometer e validar depois", "Confirmar fatos, verificar alçada e regra antes de comprometer a empresa", "Recusar qualquer exceção sem ouvir o contexto", "Transferir para outra área sem explicar o caso"], 1, "Urgência pede velocidade com contexto, regra e alçada. Prometer antes de validar aumenta risco."),
  q("01-bem-vindo-atlasgr", 2, "Qual comportamento representa melhor Transparência?", ["Comunicar cedo um risco relevante e o que ainda está em validação", "Esconder uma falha até encontrar solução completa", "Enviar todas as informações para todos", "Evitar registrar dúvidas para não parecer inseguro"], 0, "Transparência é comunicar o que importa com precisão, inclusive incertezas e riscos."),
  q("01-bem-vindo-atlasgr", 3, "Simplicidade, na prática, significa:", ["Eliminar controles para ganhar velocidade", "Reduzir atrito preservando os controles essenciais", "Usar sempre o menor número de pessoas", "Evitar documentação"], 1, "Simplificar não é remover segurança; é tornar o processo mais claro e eficiente."),
  q("01-bem-vindo-atlasgr", 4, "Atitude de Dono NÃO significa:", ["Assumir responsabilidade pelo problema", "Propor alternativas", "Decidir fora da própria alçada para mostrar iniciativa", "Escalar com contexto quando necessário"], 2, "Responsabilidade inclui reconhecer limites de alçada."),
  q("01-bem-vindo-atlasgr", 5, "Qual handoff entre áreas é mais útil?", ["'Vejam isso urgente'", "'Cliente reclamou, resolvam'", "Contexto, o que já foi validado, risco, responsável esperado e próximo passo", "Encaminhar toda a conversa sem resumo"], 2, "Handoff bom preserva contexto e reduz retrabalho."),
  q("01-bem-vindo-atlasgr", 6, "Quando treinamento e procedimento operacional vigente divergirem, o que fazer?", ["Seguir o treinamento porque foi certificado", "Escolher a versão mais simples", "Validar a regra vigente com a liderança responsável antes de executar", "Executar metade de cada orientação"], 2, "Procedimentos vigentes são a referência para execução específica."),
  q("01-bem-vindo-atlasgr", 7, "Qual frase separa melhor fato de hipótese?", ["'Houve roubo' quando só existe perda de sinal", "'Perda de comunicação identificada; causa ainda em validação'", "'Provavelmente é problema do rastreador'", "'Não há risco' sem checagem"], 1, "A linguagem deve refletir o nível real de evidência."),
  q("01-bem-vindo-atlasgr", 8, "Qual é a melhor forma de escalar uma situação fora da sua alçada?", ["Passar apenas o problema", "Esperar até alguém perguntar", "Levar contexto, evidências, impacto e uma recomendação", "Tomar a decisão e avisar depois"], 2, "Escalada com recomendação acelera decisão sem ultrapassar alçada."),
  q("01-bem-vindo-atlasgr", 9, "O valor Inovação é melhor demonstrado quando:", ["Uma nova tecnologia é adotada porque está em alta", "Uma melhoria resolve problema real e seu efeito pode ser medido", "A equipe troca de ferramenta com frequência", "Todo processo manual é automaticamente eliminado"], 1, "Inovação útil está ligada a problema, resultado e sustentação."),
  q("01-bem-vindo-atlasgr", 10, "O principal objetivo deste onboarding é:", ["Memorizar todas as frases institucionais", "Aprender a tomar decisões melhores dentro de contexto, regra e responsabilidade", "Substituir treinamento prático da área", "Aumentar automaticamente a alçada do colaborador"], 1, "O treinamento constrói entendimento e julgamento; não substitui prática nem alçada."),
];

export const quiz02 = [
  q("02-mercado-logistica", 1, "Qual descrição melhor representa uma operação logística?", ["Apenas o deslocamento do caminhão", "Fluxo de mercadoria, informação, responsabilidade e decisões do planejamento ao encerramento", "Somente o processo de entrega", "A soma de rastreador e motorista"], 1, "Logística é um fluxo ponta a ponta, não apenas transporte físico."),
  q("02-mercado-logistica", 2, "Duas empresas têm o mesmo volume de viagens. O que é correto concluir?", ["Têm a mesma complexidade", "Têm o mesmo risco", "Volume sozinho não permite concluir complexidade ou risco", "Precisam da mesma estrutura operacional"], 2, "Variabilidade, consequência, carga, rota e regras mudam a operação."),
  q("02-mercado-logistica", 3, "Qual papel descreve melhor o embarcador?", ["Quem necessariamente dirige o veículo", "Quem possui ou contrata o transporte da mercadoria", "Quem fornece qualquer rastreador", "Quem sempre aprova toda exceção"], 1, "O embarcador está associado à mercadoria e à contratação do transporte; responsabilidades específicas variam."),
  q("02-mercado-logistica", 4, "Por que é importante definir uma fonte da verdade?", ["Para reduzir quantidade de usuários", "Para evitar versões concorrentes da mesma informação", "Para eliminar integrações", "Para impedir qualquer uso de planilhas"], 1, "Uma fonte oficial reduz conflito entre dados e decisões."),
  q("02-mercado-logistica", 5, "Qual fator pode aumentar complexidade mesmo com baixo volume?", ["Poucas exceções e rota única", "Múltiplas regras, paradas e integrações", "Operação padronizada", "Baixa variabilidade"], 1, "Complexidade cresce com variabilidade, exceções e pontos de decisão."),
  q("02-mercado-logistica", 6, "Uma viagem foi entregue, mas não encerrada corretamente no sistema. Qual impacto é provável?", ["Nenhum, porque a carga chegou", "Histórico e indicadores podem ficar inconsistentes", "O veículo deixa de existir", "A transportadora perde automaticamente o contrato"], 1, "Encerramento faz parte da qualidade do dado e do ciclo operacional."),
  q("02-mercado-logistica", 7, "Antes de classificar uma operação como 'simples', o que é mais adequado?", ["Olhar apenas quantidade de viagens", "Entender atores, regras, carga, rota, exceções e sistemas", "Comparar apenas faturamento", "Perguntar somente o tipo de caminhão"], 1, "Contexto define complexidade melhor que um único indicador."),
  q("02-mercado-logistica", 8, "Qual sequência representa melhor o ciclo de uma viagem?", ["Monitorar → planejar → cadastrar → entregar", "Planejar → validar → executar → tratar exceções → confirmar entrega → encerrar", "Entregar → cadastrar → monitorar", "Rastrear → faturar → planejar"], 1, "O ciclo começa antes da viagem e termina com encerramento e registro."),
  q("02-mercado-logistica", 9, "Em operação terceirizada, qual risco de governança aumenta?", ["Não existir nenhum motorista", "Contexto e responsabilidade se perderem entre empresas e sistemas", "A carga não precisar de regra", "O cliente não precisar de indicadores"], 1, "Mais participantes tornam handoffs e responsabilidade ainda mais importantes."),
  q("02-mercado-logistica", 10, "Qual pergunta ajuda mais a entender uma operação nova?", ["'Quantos caminhões vocês têm?' como única pergunta", "'Como a viagem nasce, quem participa e onde surgem as principais exceções?'", "'Qual software vocês querem comprar?'", "'Quem é o concorrente atual?'"], 1, "A pergunta mapeia fluxo, atores e exceções antes da solução."),
];

export const quiz03 = [
  q("03-gerenciamento-risco", 1, "Qual é a principal diferença entre rastreamento e gerenciamento de risco?", ["Rastreamento usa mapa e GR não", "GR combina dado, regra, contexto e resposta; rastreamento é uma fonte de localização/informação", "São sinônimos", "GR só existe após um sinistro"], 1, "Gerenciamento de risco transforma informação em controle e ação."),
  q("03-gerenciamento-risco", 2, "Um alerta indica desvio de rota. Isso prova que ocorreu um sinistro?", ["Sim, sempre", "Não; é um sinal que precisa ser validado e tratado conforme regra", "Sim, se o veículo estiver em movimento", "Não, então pode ser ignorado"], 1, "Alerta não é conclusão; ele aciona avaliação e procedimento."),
  q("03-gerenciamento-risco", 3, "Ao consultar um PGR, qual conjunto é mais importante identificar?", ["Cor do documento e quantidade de páginas", "Condição, critério, ação, responsável e tratamento de exceção", "Somente nome do cliente", "Apenas valor da carga"], 1, "Regra precisa ser convertida em condições e ações executáveis."),
  q("03-gerenciamento-risco", 4, "Por que não é seguro tratar um PGR como regra universal?", ["Porque PGR não tem utilidade", "Porque requisitos podem variar por cliente, operação, contrato, carga e seguradora", "Porque só a TI pode lê-lo", "Porque todos mudam diariamente"], 1, "A aplicação depende do contexto específico e da versão vigente."),
  q("03-gerenciamento-risco", 5, "Qual comunicação é mais adequada diante de perda de sinal ainda não explicada?", ["'Roubo confirmado'", "'Perda de comunicação identificada; causa em validação e procedimento acionado'", "'Sem risco'", "'É jammer'"], 1, "A mensagem separa evidência de hipótese."),
  q("03-gerenciamento-risco", 6, "O que fazer se o dado crítico parece desatualizado?", ["Tomar decisão como se fosse atual", "Validar horário, fonte e sinais adicionais antes de concluir", "Apagar o alerta", "Esperar indefinidamente"], 1, "Qualidade e atualidade do dado fazem parte da análise."),
  q("03-gerenciamento-risco", 7, "Qual sequência representa melhor o tratamento de um evento?", ["Supor causa → comunicar → validar", "Validar contexto → comparar com regra → agir → escalar quando necessário → registrar", "Registrar → ignorar → encerrar", "Chamar cliente → definir regra depois"], 1, "O tratamento combina evidência, regra, ação e rastreabilidade."),
  q("03-gerenciamento-risco", 8, "Quando urgência justifica criar uma exceção não prevista?", ["Sempre que o cliente pressionar", "Nunca automaticamente; exceção exige mecanismo e alçada adequados", "Sempre que o operador for experiente", "Quando houver atraso"], 1, "Urgência não cria autorização."),
  q("03-gerenciamento-risco", 9, "Qual é o risco de esperar certeza absoluta antes de qualquer ação?", ["Nenhum", "Pode atrasar uma ação preventiva exigida pelo procedimento", "Reduz sempre o risco", "Elimina falsos positivos sem custo"], 1, "Algumas regras existem justamente para agir antes de haver certeza total."),
  q("03-gerenciamento-risco", 10, "O que torna uma decisão de risco auditável?", ["Ter sido tomada por alguém experiente", "Evidência, regra consultada, ação, responsável e registro do desfecho", "Ter sido rápida", "Ter sido comunicada por telefone"], 1, "Rastreabilidade permite revisão e continuidade."),
];

export const quiz04 = [
  q("04-produtos-atlasgr", 1, "Qual é o melhor ponto de partida para apresentar uma solução ATLASGR?", ["A lista completa de produtos", "O problema e o processo atual do cliente", "O preço mais baixo", "A história da empresa"], 1, "Solução relevante nasce da necessidade, não do catálogo."),
  q("04-produtos-atlasgr", 2, "Qual sequência traduz melhor valor?", ["Produto → slogan → desconto", "Problema → capacidade → mudança esperada → métrica", "Feature → superlativo → contrato", "Tecnologia → promessa → implantação"], 1, "Essa estrutura conecta funcionalidade a resultado verificável."),
  q("04-produtos-atlasgr", 3, "Um alerta de tempo excedido é exemplo de:", ["Benefício", "Funcionalidade", "Métrica financeira", "Garantia de resultado"], 1, "A funcionalidade produz um sinal; o benefício depende de como ele melhora o processo."),
  q("04-produtos-atlasgr", 4, "Qual frase é mais segura em uma conversa sobre integração?", ["'Integramos qualquer sistema em poucos dias'", "'Precisamos validar sistema, dados e escopo antes de confirmar comportamento e prazo'", "'API resolve tudo'", "'Se tem internet, integra'"], 1, "Integração depende de requisitos e validação técnica."),
  q("04-produtos-atlasgr", 5, "Por que apresentar o portfólio inteiro pode ser ruim?", ["Porque o cliente não pode contratar mais de uma solução", "Porque aumenta complexidade sem necessariamente responder à prioridade", "Porque todos os produtos são iguais", "Porque impede demonstração"], 1, "Seleção deve refletir problema e estágio da decisão."),
  q("04-produtos-atlasgr", 6, "Qual exemplo diferencia benefício de evidência?", ["Benefício: alerta; evidência: tela", "Benefício: identificar exceção mais cedo; evidência: tempo médio até identificação", "Benefício: API; evidência: integração", "Benefício: software; evidência: proposta"], 1, "Benefício descreve mudança; evidência mede se ela aconteceu."),
  q("04-produtos-atlasgr", 7, "Quando duas soluções se complementam de verdade?", ["Quando têm nomes diferentes", "Quando atuam em etapas conectadas do processo e o fluxo de dados/responsabilidades funciona", "Quando são vendidas juntas", "Quando usam a mesma cor"], 1, "Complementaridade depende de processo e integração, não de pacote comercial."),
  q("04-produtos-atlasgr", 8, "Qual promessa deve ser evitada sem dados e contexto?", ["'Vamos avaliar a integração'", "'A solução reduzirá seu custo em X%'", "'Vamos mapear o processo'", "'O resultado precisa ser medido'"], 1, "Resultado numérico sem base é uma promessa não sustentada."),
  q("04-produtos-atlasgr", 9, "O cliente relata fraude cadastral e baixa visibilidade de viagens. Qual abordagem é melhor?", ["Escolher um produto aleatório", "Separar as dores, entender causa/impacto e mapear capacidades complementares", "Vender apenas o produto mais caro", "Falar somente de rastreamento"], 1, "Dores diferentes podem exigir frentes diferentes e um desenho integrado."),
  q("04-produtos-atlasgr", 10, "O que deve ser validado antes de prometer uma combinação de soluções?", ["Apenas o logo do cliente", "Processo, dados, integrações, escopo e responsabilidades", "Somente prazo desejado", "Número de usuários"], 1, "Valor depende da execução entre as soluções."),
];

export const quiz05 = [
  q("05-software-logistico", 1, "Antes de agir sobre um alerta do sistema, qual validação é essencial?", ["A cor do card", "Viagem/veículo, horário do dado, contexto e regra aplicável", "Quantidade de usuários online", "Nome do gestor"], 1, "Decisão exige dado atual e contexto correto."),
  q("05-software-logistico", 2, "Por que controles paralelos podem ser problemáticos?", ["Porque planilhas nunca funcionam", "Porque criam versões concorrentes e dificultam rastreabilidade", "Porque o sistema deixa de abrir", "Porque aumentam o tamanho do monitor"], 1, "Fontes concorrentes geram conflito e dados desatualizados."),
  q("05-software-logistico", 3, "Tempo elevado em um alvo significa automaticamente falha do motorista?", ["Sim", "Não; exige referência, motivo e contexto", "Sim, se passar 10 minutos", "Não, portanto nunca importa"], 1, "Permanência é um indicador que precisa de expectativa e causa."),
  q("05-software-logistico", 4, "Qual é a utilidade de comparar tempo atual com tempo esperado?", ["Criar ranking de usuários", "Transformar permanência em sinal de exceção ou gargalo", "Eliminar o planejamento", "Definir o valor da carga"], 1, "A referência dá significado ao número."),
  q("05-software-logistico", 5, "Um alerta de temperatura fora da faixa deve ser tratado como perda certa da carga?", ["Sim", "Não; é preciso validar faixa, duração, sensor, produto e procedimento", "Sim, se houver GPS", "Não; alertas de temperatura são apenas informativos"], 1, "O alerta inicia avaliação, não determina sozinho o desfecho."),
  q("05-software-logistico", 6, "Qual sinal pode indicar problema de qualidade do dado?", ["Última atualização muito antiga", "Viagem com destino definido", "Usuário autenticado", "Existência de um dashboard"], 0, "Dado antigo pode não representar o estado atual."),
  q("05-software-logistico", 7, "O que mais contribui para o Atlas Connect funcionar como fonte central?", ["Manter o estado da viagem e os tratamentos atualizados", "Duplicar tudo em chats", "Evitar encerrar viagens", "Registrar somente exceções graves"], 0, "Confiabilidade depende de disciplina de uso e atualização do fluxo."),
  q("05-software-logistico", 8, "Qual leitura de permanência é mais completa?", ["'Está há 80 min'", "'Está há 80 min, esperado 45; motivo em validação; impacto na janela X; ação Y'", "'Motorista atrasou'", "'Sistema marcou vermelho'"], 1, "Contexto transforma métrica em decisão."),
  q("05-software-logistico", 9, "Qual papel o software NÃO deve assumir sozinho?", ["Centralizar informação", "Apoiar visibilidade", "Substituir totalmente julgamento, regra e responsabilidade humana", "Exibir alertas"], 2, "Sistema apoia a decisão; processo e alçada continuam necessários."),
  q("05-software-logistico", 10, "Ao encerrar uma viagem, por que o registro final importa?", ["Apenas para estética do painel", "Para preservar histórico, indicadores e estado coerente da operação", "Para apagar alertas anteriores", "Para reduzir o número de clientes"], 1, "Encerramento correto mantém a base confiável para operação e análise."),
];
