import { question as q } from "./helpers";

export const quiz11 = [
  q("11-operacao", 1, "Três alertas chegam ao mesmo tempo. Como priorizar?", ["Sempre pela ordem de chegada", "Por consequência possível, sensibilidade ao tempo, evidência e regra vigente", "Pelo cliente que reclama mais", "Pelo alerta com texto mais longo"], 1, "Prioridade operacional considera risco e tempo, não apenas cronologia."),
  q("11-operacao", 2, "Priorizar um evento significa:", ["Abandonar os demais", "Dar atenção proporcional sem perder responsável e retorno dos outros eventos", "Encerrar eventos menores sem tratar", "Transferir toda a fila"], 1, "A fila precisa continuar controlada mesmo quando um evento domina atenção."),
  q("11-operacao", 3, "Qual é a primeira checagem diante de um alerta?", ["Acionar todos os contatos", "Identificar viagem/veículo, horário, fonte e contexto", "Concluir a causa", "Alterar a regra"], 1, "A validação inicial evita agir sobre evento ou registro errado."),
  q("11-operacao", 4, "Qual comunicação é mais acionável?", ["'Estamos verificando'", "'Perda de comunicação há X min; última posição Y; procedimento Z acionado; próximo marco em N min'", "'Deu problema'", "'Provavelmente é grave'"], 1, "Estado, evidência, ação e próximo marco reduzem ambiguidade."),
  q("11-operacao", 5, "Quando usar linguagem como 'em validação'?", ["Nunca", "Quando a evidência ainda não permite uma conclusão definitiva", "Somente com cliente", "Para evitar registrar"], 1, "A linguagem precisa refletir o grau de certeza."),
  q("11-operacao", 6, "Qual é o risco de agir cedo demais?", ["Nenhum", "Executar ação desnecessária com base em dado incompleto", "Sempre reduzir tempo", "Eliminar necessidade de procedimento"], 1, "Velocidade sem validação pode gerar erro e impacto adicional."),
  q("11-operacao", 7, "Qual é o risco de esperar certeza absoluta?", ["Nenhum", "Atrasar resposta preventiva quando a regra exige ação antes da confirmação total", "Melhorar sempre a decisão", "Evitar qualquer escalonamento"], 1, "Alguns controles existem para agir com evidência suficiente, não certeza total."),
  q("11-operacao", 8, "Um evento pode ser considerado encerrado quando:", ["O alerta some da tela", "O desfecho está confirmado/registrado e não há ação pendente sem responsável", "O turno acaba", "O cliente para de perguntar"], 1, "Encerramento é operacional e rastreável."),
  q("11-operacao", 9, "O que este módulo NÃO substitui?", ["Raciocínio de prioridade", "PGR, POP e instrução operacional vigente", "Comunicação", "Registro"], 1, "O conteúdo ensina método; execução específica segue regra vigente."),
  q("11-operacao", 10, "Qual hábito melhora continuidade entre turnos?", ["Guardar contexto na memória", "Registrar estado, ações, pendências e responsável de forma clara", "Usar mensagens pessoais", "Encerrar tudo antes da troca"], 1, "Handoff operacional precisa preservar o estado real do caso."),
];

export const quiz12 = [
  q("12-compliance", 1, "Um parceiro pede dados de motorista por mensagem. Qual é a primeira pergunta?", ["'Você tem pressa?'", "'Qual a finalidade e quais dados são realmente necessários?'", "'Qual seu cargo?'", "'Você prefere PDF ou foto?'"], 1, "Finalidade e necessidade orientam tratamento de dados."),
  q("12-compliance", 2, "Ter acesso a um cadastro significa:", ["Poder usar o dado para qualquer finalidade", "Ter capacidade técnica de acesso, ainda sujeita a finalidade, permissão e política", "Poder enviar print", "Poder manter cópia pessoal"], 1, "Acesso não elimina regras de tratamento."),
  q("12-compliance", 3, "Qual prática aplica minimização de dados?", ["Enviar cadastro completo", "Compartilhar apenas a informação necessária para a ação autorizada", "Exportar a base", "Copiar o grupo inteiro"], 1, "Minimização limita exposição ao necessário."),
  q("12-compliance", 4, "Por que credenciais individuais importam?", ["Somente por estética", "Permitem rastrear ações e aplicar permissões por função", "Para aumentar senhas", "Para impedir trabalho em equipe"], 1, "Identidade individual sustenta controle de acesso e auditoria."),
  q("12-compliance", 5, "Um colega precisa de acesso e pede sua senha. O que fazer?", ["Compartilhar por alguns minutos", "Orientar a solicitação do acesso adequado e não compartilhar credencial", "Mandar somente o código de MFA", "Deixar a sessão aberta"], 1, "Credenciais não devem ser compartilhadas como atalho."),
  q("12-compliance", 6, "Urgência operacional muda o quê?", ["A autorização", "A prioridade e velocidade de resposta, não os controles essenciais", "A finalidade do dado", "A identidade do usuário"], 1, "Urgência não cria permissão."),
  q("12-compliance", 7, "Você enviou um dado para destinatário errado. Qual é a melhor reação?", ["Apagar sua mensagem e não contar", "Interromper novos compartilhamentos e reportar pelo fluxo de incidente", "Pedir ao destinatário para esquecer", "Esperar para ver se haverá problema"], 1, "Reporte precoce permite contenção e resposta adequada."),
  q("12-compliance", 8, "Qual local é mais adequado para informação operacional sensível?", ["Canal corporativo autorizado e com acesso necessário", "Grupo pessoal", "Arquivo público", "Conta compartilhada"], 0, "Canal e controle de acesso precisam ser compatíveis com a sensibilidade."),
  q("12-compliance", 9, "Uma exceção recorrente é sinal de que:", ["Deve virar regra informal", "Pode existir um problema de processo que precisa de revisão governada", "Compliance não funciona", "O registro deve ser removido"], 1, "Recorrência pode revelar necessidade de melhorar processo, não normalizar atalho."),
  q("12-compliance", 10, "Qual sequência é mais segura antes de compartilhar dado?", ["Pressa → envio → validação", "Finalidade → necessidade → destinatário/canal → mínimo necessário → registro", "Acesso → print → grupo", "Pedido do cliente → envio automático"], 1, "A sequência organiza controles básicos de privacidade e segurança."),
];

export const quiz13 = [
  q("13-tecnologia", 1, "Quando uma tecnologia cria valor?", ["Quando é nova", "Quando melhora um problema ou resultado de forma verificável", "Quando usa IA", "Quando substitui pessoas"], 1, "Tecnologia precisa estar ligada a problema e métrica."),
  q("13-tecnologia", 2, "Qual camada vem antes de uma decisão automatizada?", ["Marketing", "Dados e processamento/regra", "Certificado", "Ranking"], 1, "A ação depende das camadas de coleta, transmissão e interpretação."),
  q("13-tecnologia", 3, "Se um valor exibido está errado, qual investigação é melhor?", ["Assumir bug da interface", "Verificar coleta, transmissão, integração, regra e interface por camadas", "Trocar o usuário", "Apagar o histórico"], 1, "Separar camadas acelera causa raiz."),
  q("13-tecnologia", 4, "Qual tarefa é melhor candidata à automação?", ["Decisão ambígua e irreversível", "Processo repetitivo com regra clara, baixo impacto e resultado mensurável", "Qualquer tarefa humana", "Decisão sem dados"], 1, "Clareza, reversibilidade e medição reduzem risco de automação."),
  q("13-tecnologia", 5, "Por que falso negativo pode ser crítico em classificação de alertas?", ["Porque aumenta a cor do dashboard", "Porque um evento relevante pode não receber atenção necessária", "Porque gera mais logs", "Porque melhora precisão"], 1, "Erro de omissão pode ocultar evento que exige ação."),
  q("13-tecnologia", 6, "Antes de implantar uma IA operacional, o que deve ser definido?", ["Somente o fornecedor", "Métrica, dados de teste, erros aceitáveis, supervisão e fallback", "Somente preço", "Somente prompt"], 1, "Controles precisam existir antes da escala."),
  q("13-tecnologia", 7, "Qual afirmação sobre respostas de IA é mais segura?", ["Texto fluido prova correção", "A confiança deve depender de fonte, validação e risco da decisão", "IA nunca erra", "IA sempre precisa ser proibida"], 1, "Fluidez não é evidência de verdade."),
  q("13-tecnologia", 8, "Automação de uma regra incorreta tende a:", ["Corrigir a regra", "Escalar o erro com maior velocidade e volume", "Eliminar impacto", "Gerar sempre revisão humana"], 1, "Automação amplia o efeito do desenho existente."),
  q("13-tecnologia", 9, "Qual métrica ajuda a avaliar automação?", ["Quantidade de animações", "Tempo, erro, retrabalho, intervenção humana ou qualidade do resultado", "Número de telas", "Tamanho do código"], 1, "Métrica deve refletir o problema que motivou a automação."),
  q("13-tecnologia", 10, "Qual princípio é adequado para decisões de alto impacto?", ["Automatizar primeiro", "Aplicar supervisão e barreiras proporcionais à consequência do erro", "Usar somente confiança do modelo", "Evitar logs"], 1, "Controle deve crescer com o risco da decisão."),
];

export const quiz14 = [
  q("14-casos-reais", 1, "Qual é a primeira disciplina ao analisar um case?", ["Começar pelo resultado", "Reconstruir contexto e informação disponível no momento da decisão", "Procurar culpado", "Copiar a ação"], 1, "O resultado conhecido distorce nossa leitura do passado."),
  q("14-casos-reais", 2, "O que é viés de retrospectiva?", ["Esquecer o caso", "Depois do resultado, acreditar que os sinais anteriores eram mais óbvios do que realmente eram", "Usar dados históricos", "Registrar o caso"], 1, "Saber o desfecho faz a decisão parecer previsível."),
  q("14-casos-reais", 3, "Um case terminou bem. O que NÃO pode ser concluído automaticamente?", ["Houve um resultado positivo", "Toda ação tomada deve virar regra universal", "Existia um contexto", "Podemos estudar a decisão"], 1, "Resultado positivo não valida universalmente o método."),
  q("14-casos-reais", 4, "Qual pergunta ajuda a separar lição de contexto?", ["'Funcionou?'", "'O que seria diferente se rota, cliente, carga ou regra mudassem?'", "'Quem contou a história?'", "'Quantos slides há?'"], 1, "Variação de contexto mostra limites de transferibilidade."),
  q("14-casos-reais", 5, "Como tratar dados sensíveis em case de treinamento?", ["Expor detalhes para ficar realista", "Usar versão aprovada e anonimizar quando identificação não for necessária", "Publicar prints", "Compartilhar nome de motorista"], 1, "Aprendizado não justifica exposição desnecessária."),
  q("14-casos-reais", 6, "Qual saída transforma case em melhoria?", ["Somente contar a história", "Converter lição em checklist, pergunta, indicador ou ajuste governado", "Criar regra informal", "Premiar quem participou"], 1, "Aprendizado precisa alterar comportamento ou sistema de forma adequada."),
  q("14-casos-reais", 7, "Todo incidente deve gerar nova regra?", ["Sim", "Não; primeiro avalie causa, frequência e se o controle existente já era suficiente", "Somente se houver perda", "Somente se cliente pedir"], 1, "Criar regra para cada exceção aumenta complexidade sem necessariamente reduzir risco."),
  q("14-casos-reais", 8, "Qual estrutura de análise é mais completa?", ["Resultado → elogio", "Contexto → sinais → alternativas → decisão → resultado → limites → lição", "Pessoa → culpa → regra", "Problema → produto"], 1, "A estrutura preserva o raciocínio e os limites do caso."),
  q("14-casos-reais", 9, "Por que evitar generalizar um caso de fraude para perfis semelhantes?", ["Porque casos não servem", "Porque decisões devem permanecer individuais, baseadas em evidência e critérios adequados", "Porque dados nunca podem ser usados", "Porque clientes não gostam"], 1, "Generalização indevida cria julgamento não sustentado."),
  q("14-casos-reais", 10, "Qual é o objetivo principal do módulo de casos?", ["Memorizar histórias", "Melhorar a qualidade da próxima decisão", "Encontrar culpados", "Substituir procedimentos"], 1, "O case é ferramenta de aprendizagem aplicada."),
];

export const quiz15 = [
  q("15-preparacao-final", 1, "Qual método de revisão testa melhor disponibilidade do conhecimento?", ["Reler tudo várias vezes", "Tentar recuperar e explicar antes de consultar", "Apenas assistir vídeos", "Sublinhar títulos"], 1, "Recuperação ativa revela lacunas que a familiaridade da releitura pode esconder."),
  q("15-preparacao-final", 2, "Qual sequência conecta melhor a jornada operacional?", ["Produto → preço → certificado", "Cliente/contexto → cadastro → planejamento/regras → sistemas → monitoramento → tratamento → registro", "Monitoramento → cliente → cadastro", "Prova → sistema → venda"], 1, "A visão sistêmica integra os módulos em um fluxo de trabalho."),
  q("15-preparacao-final", 3, "O que uma boa justificativa de decisão inclui?", ["Somente a resposta", "Fato observado, regra/critério, risco, ação e escalonamento quando necessário", "Cargo de quem decidiu", "Tempo de empresa"], 1, "Justificativa mostra raciocínio, não apenas resultado."),
  q("15-preparacao-final", 4, "Uma nota alta no quiz significa que:", ["A pessoa pode executar qualquer processo", "O conhecimento avaliado foi bem respondido, mas prática e alçada continuam necessárias", "O treinamento acabou para sempre", "Não precisa revisar"], 1, "Avaliação teórica não substitui autorização e desempenho prático."),
  q("15-preparacao-final", 5, "Como usar o mapa de domínio antes da prova?", ["Ignorar notas menores", "Priorizar categorias mais fracas e praticar cenários integrados", "Revisar apenas o módulo favorito", "Aumentar a nota manualmente"], 1, "O painel ajuda a concentrar esforço onde existe maior lacuna."),
  q("15-preparacao-final", 6, "Qual cenário demonstra visão sistêmica?", ["Explicar um termo isolado", "Conectar cliente, risco, dados, sistema, compliance, ação e registro em uma mesma situação", "Memorizar datas", "Listar produtos"], 1, "Problemas reais atravessam múltiplas disciplinas."),
  q("15-preparacao-final", 7, "Se você não lembra uma regra específica durante a prática, o melhor comportamento é:", ["Inventar uma regra provável", "Reconhecer a lacuna e consultar a fonte vigente antes de uma decisão dependente dela", "Executar pela memória", "Evitar registrar"], 1, "Saber localizar a fonte correta faz parte da competência."),
  q("15-preparacao-final", 8, "O certificado da Academia aumenta automaticamente a alçada operacional?", ["Sim", "Não; alçada depende de função, acessos, prática e regras da área", "Sim, por 90 dias", "Somente em emergência"], 1, "Certificação valida etapa de aprendizagem, não autorização universal."),
  q("15-preparacao-final", 9, "Qual é um bom compromisso pós-treinamento?", ["Nunca mais revisar", "Escolher um comportamento para aplicar e uma área para reforçar", "Guardar o certificado", "Refazer apenas perguntas fáceis"], 1, "Transferência para o trabalho mantém aprendizagem ativa."),
  q("15-preparacao-final", 10, "Qual frase melhor resume a Academia V2?", ["Concluir módulos é o objetivo", "Aprender, aplicar, receber feedback e provar domínio para decidir melhor", "Gamificação é mais importante que conteúdo", "A prova substitui experiência"], 1, "A jornada foi redesenhada para transferência e domínio."),
];
