import type { ModuleMeta } from "@/lib/types";

export const moduleMetas: ModuleMeta[] = [
  {
    slug: "01-bem-vindo-atlasgr",
    number: 1,
    title: "Bem-vindo à ATLASGR",
    shortDescription: "História, propósito, valores, cultura e organograma da empresa.",
    durationMinutes: 40,
    status: "ready",
    category: "Fundamentos",
    imageUrl: "/brand/module_banner.jpg",
    imageCaption: "Cultura Organizacional e Propósito AtlasGR",
  },
  {
    slug: "02-mercado-logistica",
    number: 2,
    title: "Mercado de Logística",
    shortDescription: "Supply chain, transportadoras, embarcadores e tipos de carga e operação.",
    durationMinutes: 35,
    status: "ready",
    category: "Fundamentos",
    imageUrl: "/brand/modules/02-logistica.svg",
    imageCaption: "Cadeia de Suprimentos e Rodovias Nacionais",
  },
  {
    slug: "03-gerenciamento-risco",
    number: 3,
    title: "Gerenciamento de Risco",
    shortDescription: "Do conceito básico ao avançado: PGR, apólice, sinistro e o papel da Central.",
    durationMinutes: 55,
    status: "ready",
    category: "Fundamentos",
    imageUrl: "/brand/modules/03-risco.svg",
    imageCaption: "Prevenção de Perdas, PGR e Monitoramento",
  },
  {
    slug: "04-produtos-atlasgr",
    number: 4,
    title: "Produtos ATLASGR",
    shortDescription: "Visão geral do portfólio: gerenciamento de risco, tecnologia, perfil securitário e bases dedicadas.",
    durationMinutes: 45,
    status: "ready",
    category: "Soluções ATLASGR",
    imageUrl: "/brand/modules/04-produtos.svg",
    imageCaption: "Ecossistema de Soluções AtlasGR",
  },
  {
    slug: "05-software-logistico",
    number: 5,
    title: "Software Logístico — Sistema Atlas Connect",
    shortDescription: "Telas, funcionalidades e fluxo de trabalho do sistema Atlas Connect.",
    durationMinutes: 50,
    status: "ready",
    category: "Soluções ATLASGR",
    imageUrl: "/brand/modules/05-connect.svg",
    imageCaption: "Torre de Controle Atlas Connect em Tempo Real",
  },
  {
    slug: "06-atlas-profile",
    number: 6,
    title: "Atlas Profile",
    shortDescription: "Background check, biometria e compliance na análise de motoristas e veículos.",
    durationMinutes: 35,
    status: "ready",
    category: "Soluções ATLASGR",
    imageUrl: "/brand/modules/06-profile.svg",
    imageCaption: "Biometria e Análise Cadastral Inteligente",
  },
  {
    slug: "07-integracoes",
    number: 7,
    title: "Integrações",
    shortDescription: "Como o Atlas Connect conversa com ERP, TMS e rastreadores de diferentes fabricantes.",
    durationMinutes: 30,
    status: "ready",
    category: "Soluções ATLASGR",
    imageUrl: "/brand/modules/07-integracoes.svg",
    imageCaption: "Conectores de API, ERP, TMS e Telemetria Multimarcas",
  },
  {
    slug: "08-clientes",
    number: 8,
    title: "Clientes",
    shortDescription: "Perfis de cliente atendidos pela Atlas: transportadoras, embarcadores e segmentos.",
    durationMinutes: 30,
    status: "ready",
    category: "Mercado e clientes",
    imageUrl: "/brand/modules/08-clientes.svg",
    imageCaption: "Perfis de Embarcadores e Transportadoras Atendidas",
  },
  {
    slug: "09-processo-comercial",
    number: 9,
    title: "Processo Comercial",
    shortDescription: "ICP, persona, dores, objeções, diferenciais competitivos e argumentação.",
    durationMinutes: 40,
    status: "ready",
    category: "Mercado e clientes",
    imageUrl: "/brand/modules/09-comercial.svg",
    imageCaption: "Funil Comercial B2B e Qualificação de Leadd",
  },
  {
    slug: "10-termos-tecnicos",
    number: 10,
    title: "Termos Técnicos",
    shortDescription: "Glossário consolidado com os termos usados no dia a dia da Central e do mercado.",
    durationMinutes: 30,
    status: "ready",
    category: "Excelência operacional",
    imageUrl: "/brand/modules/10-glossario.svg",
    imageCaption: "Dicionário de Jargões e Termos de Operação Logística",
  },
  {
    slug: "11-operacao",
    number: 11,
    title: "Operação",
    shortDescription: "Fluxos, monitoramento, checklist, alertas e eventos do dia a dia da Central.",
    durationMinutes: 45,
    status: "ready",
    category: "Excelência operacional",
    imageUrl: "/brand/modules/11-operacao.svg",
    imageCaption: "Procedimento Operacional Padrão (POP) e Pronta Resposta",
  },
  {
    slug: "12-compliance",
    number: 12,
    title: "Compliance",
    shortDescription: "LGPD, segurança da informação, sigilo e boas práticas internas.",
    durationMinutes: 30,
    status: "ready",
    category: "Excelência operacional",
    imageUrl: "/brand/modules/12-compliance.svg",
    imageCaption: "Proteção de Dados, LGPD e Segurança da Informação",
  },
  {
    slug: "13-tecnologia",
    number: 13,
    title: "Tecnologia",
    shortDescription: "IA, analytics e automações aplicadas ao gerenciamento de risco logístico.",
    durationMinutes: 35,
    status: "ready",
    category: "Excelência operacional",
    imageUrl: "/brand/modules/13-tecnologia.svg",
    imageCaption: "Inteligência Artificial, Predição de Risco e Analytics",
  },
  {
    slug: "14-casos-reais",
    number: 14,
    title: "Casos Reais",
    shortDescription: "Cases, recuperações e resultados operacionais da Atlas.",
    durationMinutes: 30,
    status: "ready",
    category: "Excelência operacional",
    imageUrl: "/brand/modules/14-casos.svg",
    imageCaption: "Central de Investigação C.I.A e Recuperação de Carga",
  },
  {
    slug: "15-preparacao-final",
    number: 15,
    title: "Preparação Final",
    shortDescription: "Revisão geral de todo o conteúdo antes da prova final.",
    durationMinutes: 30,
    status: "ready",
    category: "Conclusão",
    imageUrl: "/brand/modules/15-preparacao.svg",
    imageCaption: "Certificação Profissional e Formação Operacional",
  },
];

export function getModuleMeta(slug: string): ModuleMeta | undefined {
  return moduleMetas.find((m) => m.slug === slug);
}
